"""Add image generation fields to Event

Revision ID: 4f97fcb6ff17
Revises: e6bfa36aab61
Create Date: 2026-07-19 17:19:09.289155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f97fcb6ff17'
down_revision: Union[str, Sequence[str], None] = 'e6bfa36aab61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('events', sa.Column('image_public_id', sa.String(), nullable=True))
    op.add_column('events', sa.Column('image_generation_status', sa.String(), nullable=True))
    op.add_column('events', sa.Column('image_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'image_prompt')
    op.drop_column('events', 'image_generation_status')
    op.drop_column('events', 'image_public_id')
    op.drop_column('events', 'image_url')
    # ### end Alembic commands ###
