"""event_registrations_update

Revision ID: e6bfa36aab61
Revises: a5959caec39e
Create Date: 2026-07-19 16:39:08.711782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6bfa36aab61'
down_revision: Union[str, Sequence[str], None] = 'a5959caec39e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('student_uid', sa.String(), nullable=False))
    op.add_column('registrations', sa.Column('event_title', sa.String(), nullable=True))
    op.add_column('registrations', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('registrations', sa.Column('email', sa.String(), nullable=False))
    op.add_column('registrations', sa.Column('roll_number', sa.String(), nullable=False))
    op.add_column('registrations', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('registrations', sa.Column('registration_status', sa.String(), nullable=True))
    op.add_column('registrations', sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('registrations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_registrations_student_uid'), 'registrations', ['student_uid'], unique=False)
    op.create_unique_constraint('uq_student_event', 'registrations', ['student_uid', 'event_id'])
    op.drop_constraint(op.f('registrations_user_id_fkey'), 'registrations', type_='foreignkey')
    op.drop_column('registrations', 'type')
    op.drop_column('registrations', 'user_id')
    op.drop_column('registrations', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('registrations', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('registrations', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('registrations_user_id_fkey'), 'registrations', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_student_event', 'registrations', type_='unique')
    op.drop_index(op.f('ix_registrations_student_uid'), table_name='registrations')
    op.drop_column('registrations', 'updated_at')
    op.drop_column('registrations', 'registered_at')
    op.drop_column('registrations', 'registration_status')
    op.drop_column('registrations', 'notes')
    op.drop_column('registrations', 'roll_number')
    op.drop_column('registrations', 'email')
    op.drop_column('registrations', 'full_name')
    op.drop_column('registrations', 'event_title')
    op.drop_column('registrations', 'student_uid')
    # ### end Alembic commands ###
